In [29]:
import torch
torch.cuda.is_available()
device = torch.device("cuda")

In [13]:
tensor2d = torch.tensor([[1, 2, 3], [2, 3, 4]])

In [14]:
tensor2d

tensor([[1, 2, 3],
        [2, 3, 4]])

In [15]:
tensor2d.shape

torch.Size([2, 3])

In [16]:
tensor2d.T

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [19]:
import torch.nn.functional as F
from torch.autograd import grad

## Automatic differentiation

In [21]:
y = torch.tensor([1.0])
x = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

In [22]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


## Setting up a CNN

In [33]:
class PyTorchCNN(torch.nn.Module):
    def __init__(self, num_classes):
        super().__init__()

        self.num_classes = num_classes
        self.features = torch.nn.Sequential(
            torch.nn.Conv2d(...),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(...),
            torch.nn.Conv2d(...),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(...),
        )
        self.classifier = torch.nn.Sequential(
            torch.nn.Flatten(),
            torch.nn.Linear(..., num_classes)
        )

    def forward(self, x):
        x_feat = self.features(x)
        x_out = self.classifier(x_feat)
        return x_out

In [34]:
model = PyTorchCNN(num_classes=num_classes)
model = model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(num_epochs):
    model.train()
    for batch_idx, (features, targets) in enumerate(train_loader):
        features, targets = features.to(device), targets.to(device)

        ### Forward pass
        logits = model(features)
        loss = F.cross_entropy(logits, targets)

        ### Backward pass (backpropagation)
        optimizer.zero_grad() # Resets gradients to minimize accumulation
        loss.backward()

        ### Update model params
        optimizer.step()

    ### Optional eval steps
    model.eval()
    with torch.no_grad():
        valid_acc = compute_accuracy(model, valid_loader, device)
        print(f"Validation accuracy: {valid_acc * 100:.2f}%")

NameError: name 'num_classes' is not defined